apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: ericjansen@live.nl
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secrets
              key: pgadmin-secret
        - name: PGADMIN_PORT
          value: "80"
        image: dpage/pgadmin4:latest
        imagePullPolicy: IfNotPresent
        name: pgadmin
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 80
        volumeMounts:
         - name: pgadmin-config
           mountPath: /pgadmin4/servers.json
           subPath: servers.json
           readOnly: true
         - name: pgadmin-data
           mountPath: /var/lib/pgadmin
         - name: secrets
           mountPath: "/mnt/secrets-store"
           readOnly: true
        # resources:
        #   limits:
        #     memory: 4096Mi
      volumes:
      - name: pgadmin-config
        configMap:
          name: pgadmin-config
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-pvc
      - name:  secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "pgadmin-secretproviderclass"