apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-storage-class
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete # or Retain
volumeBindingMode: WaitForFirstCustomer #or Immediate
allowVolumeExpansion: true
parameters:
  storageaccounttype: Standard_LRS
  kind: managed