apiVersion: v1
kind: Service
metadata:
 name: pgadmin-service
spec:
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
 selector:
   app: pgadmin
 type: ClusterIP
# # ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pgadmin-service
# spec:
#   type: ClusterIP
#   ports:
#   - port: 80
#   selector:
#     app: pgadmin