apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-secret
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: demosecret
    type: Opaque
    data:
    - objectName: "demosecret"
      key: demosecret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2a2e75f6-63b4-4045-8f8a-dc2dfd4b6e38"
    keyvaultName: ""
    objects: |
      array:
        - |
          objectName: "demosecret"
          objectType: secret
    tenantId: "c2afb8f4-c242-45e0-8513-2cdfcb2c8cdd"
