# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: django-api-secretproviderclass
spec:
  provider: azure
  secretObjects:
    - secretName: django-api-secrets
      data:
        - key: pgadmin-secret
          objectName: pgadmin
        - key: django-env-secret
          objectName: django-secret
        - key: django-database-server-url
          objectName: django-database-server-url
        - key: COSMOS-ACCESS-KEY
          objectName: COSMOS-ACCESS-KEY
        - key: FIREBASE-CREDS
          objectName: FIREBASE-CREDS
      type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: "2a2e75f6-63b4-4045-8f8a-dc2dfd4b6e38" # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: {{ .Values.environment.keyvaultname }}
    cloudName: "AzurePublicCloud" # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: pgadmin
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: django-secret
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: django-database-server-url
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: COSMOS-ACCESS-KEY
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: FIREBASE-CREDS
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: c2afb8f4-c242-45e0-8513-2cdfcb2c8cdd # The tenant ID of the key vault
