apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-api.fullname" . }}
  annotations: 
    prometheus.io/scrape: "true"
  labels:
    {{- include "django-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "django-api.selectorLabels" . | nindent 4 }}
