name: Template - Kubernetes Helm Deploy

on:
  workflow_dispatch:
    inputs:
      working_dir:
        required: true
        type: string
        description: Working directory
      values_file:
        required: false
        type: string
        description: Location of values.yml file
      namsepsace:
        required: true
        type: string
        description: Kubernetes namespace
      release_name:
        required: true
        type: string
        description: Helm release name

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }} #./django/api #
    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: 'rg-appelent-shared'
          cluster-name: 'aks-appelent'

      - name: Deploy
        run: |
          helm upgrade --install --atomic --timeout 1m ${{ inputs.release_name }} ./django-api -f $inputs.values_file \
            --namespace $inputs.namespace --create-namespace
            #--set image.tag=${{ needs.setup.outputs.tag }}