name: Django API Build

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
    paths:
    - django/api/** 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/_docker_build.yml
    with:
      working_dir: ./django/api
      repository_name: demo
    secrets: inherit

  deploy:
    uses: ./.github/workflows/django_api_deploy.yml
    needs: [build]
    with:
      environment: development
    secrets: inherit
