name: Django API Build

on:
  workflow_dispatch:
    inputs:
      deploy_dev:
        type: boolean
        description: Deploy to development environment
      deploy_prd:
        type: boolean
        description: Deploy to production environment
  push:
    branches:
      - main
    paths:
    - django/api/** 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare_build: 
    runs-on: ubuntu-latest
    outputs:
      deploy_dev: ${{ steps.output.outputs.DEPLOY_DEV }}
    steps:
      - name: Set output vars
        id: output
        run: |
          if [[ "${{inputs.deploy_dev}}" == "true" || ${{github.event_name}} != 'workflow_dispatch' ]]; then
              echo "DEPLOY_DEV=true" >> $GITHUB_OUTPUT
          else
              echo "DEPLOY_DEV=false" >> $GITHUB_OUTPUT
          fi

  build:
    uses: ./.github/workflows/_docker_build.yml
    needs: [prepare_build]
    with:
      working_dir: ./django/api
      repository_name: django-api
    secrets: inherit

  deploy_development:
    uses: ./.github/workflows/django_api_deploy.yml
    if: ${{ needs.prepare_build.outputs.deploy_dev == 'true' }}
    needs: [build]
    with:
      environment: development
      image_tag: ${{ github.sha }}
    secrets: inherit

  deploy_production:
    uses: ./.github/workflows/django_api_deploy.yml
    if: ${{inputs.deploy_prd == true}}
    needs: [build]
    with:
      environment: production
      image_tag: ${{ github.sha }}
    secrets: inherit
