name: NextJS App Demo Build

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
    paths:
    - frontend/react/devias-kit-pro-v600-custom/** 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare_build: 
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: ls
      # - uses: Azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - uses: Azure/get-keyvault-secrets@v1
      #   with: 
      #     keyvault: "kv-appelent-shared"
      #     secrets: 'containerPassword, containerUsername'
      #   id: myGetSecretAction
      # - name: Create .env.local file
      #   run: |
      #     touch .env.local
      #     echo NEXT_PUBLIC_FB_CLIENT_API_KEY=${{ secrets.NEXT_PUBLIC_FB_CLIENT_API_KEY }} >> .env.local
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: env-local
      #     path: ./.env.local

  build:
    uses: ./.github/workflows/_docker_build.yml
    needs: [prepare_build]
    with:
      working_dir: ./frontend/react/devias-kit-pro-v600-custom
      repository_name: demo
      # artifact_name: env-local
      # artifact_path: ./frontend/react/devias-kit-pro-v600-custom
    secrets: inherit

  deploy:
    uses: ./.github/workflows/nextjs_demo_deploy.yml
    needs: [build]
    with:
      environment: development
      image_tag: latest
    secrets: inherit
